BaseFolder = 'base_folder'
PipelineType = 'pipeline_type'
PipelineClass = 'pipeline_class'
RenderSceneCreationScript = 'render_scene_creation_script'
InputSceneCreationScript = 'input_scene_creation_script'
NukeScript = 'nuke_script'
ProductTable = 'product_table'
ProductTableSheetName = 'product_table_sheet_name'
BaseScene = 'base_scene'
RenderSettings = 'render_settings'
ReplaceGermanCharacters = 'replace_german_characters'
PerspectiveCodes = 'perspective_codes'
RenderingExtension = 'rendering_extension'
PostOutputExtensions = 'post_output_extensions'

RenderScenesFolder = 'render_scenes'
InputScenesFolder = 'input_scenes'
EnvironmentScenesFolder = 'environment_scenes'
NukeScenesFolder = 'nuke_scenes'
RenderingsFolder = 'renderings'
PostFolder = 'post'
DeliveryFolder = 'delivery'

SidNaming = 'sid_naming'
RenderSceneNaming = 'render_scene_naming'
InputSceneNaming = 'input_scene_naming'
EnvironmentSceneNaming = 'environment_scene_naming'
NukeSceneNaming = 'nuke_scene_naming'
RenderingNaming = 'rendering_naming'
PostNaming = 'post_naming'
DeliveryNaming = 'delivery_naming'

Perspective = 'perspective'
SceneExtension = 'scene_extension'
Mapping = 'mapping'

BaseSceneFilename = 'base_scene_filename'
InputSceneFilename = 'input_scene_filename'
RenderSceneFilename = 'render_scene_filename'
EnvironmentSceneFilename = 'environment_scene_filename'
NukeSceneFilename = 'nuke_scene_filename'
RenderingFilename = 'rendering_filename'
PostFilename = 'post_filename'
DeliveryFilename = 'delivery_filename'

# Deadline
DeadlinePriority = 'deadline_priority'
DeadlineInputScenePool = 'deadline_input_scene_pool'
DeadlineRenderScenePool = 'deadline_render_scene_pool'
DeadlineRenderingPool = 'deadline_rendering_pool'
DeadlineNukePool = 'deadline_nuke_pool'
DeadlineDeliveryPool = 'deadline_delivery_pool'
DeadlineInputSceneTimeout = 'deadline_input_scene_timeout'
DeadlineRenderSceneTimeout = 'deadline_render_scene_timeout'
DeadlineRenderingTimeout = 'deadline_rendering_timeout'
DeadlineNukeTimeout = 'deadline_nuke_timeout'
DeadlineDeliveryTimeout = 'deadline_delivery_timeout'

# 3dsMax
Max3dsVersion = '3dsmax_version'

# Nuke
NukeVersion = 'nuke_version'