version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
        - mongo
        - rabbitmq

  rabbitmq:
    image: rabbitmq:3.8.19-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    environment:
    - "RABBITMQ_DEFAULT_USER=mdmanager"
    - "RABBITMQ_DEFAULT_PASS=rabbitmq"

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=example
      - ME_CONFIG_BASICAUTH_USERNAME=
      - ME_CONFIG_BASICAUTH_PASSWORD=
    depends_on:
      - mongo
